application:
  name: nweapp
  project: nweapp-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: my-psql
routers:
- name: nweapp-xamoozzxc
  routes:
  - application_name: nweapp
    paths:
    - /
